"""Approval pins are trusted test inputs here, never generated by receipt data."""
from __future__ import annotations

import copy
import hashlib
import json
import os
import sys
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import ccxt_certification as certification
import ccxt_certification_evidence as evidence
from ccxt_profiles import PROFILES


class CertificationEvidenceTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.executor = self.root / 'executor'
        self.sdk = self.root / 'sdk'
        self.receipts = self.root / 'receipts'
        for directory in (self.executor, self.sdk, self.receipts):
            directory.mkdir()
        (self.executor / 'ccxt_certification.py').write_text('# executor fixture\n', encoding='utf-8')
        (self.executor / 'adapter.py').write_text('# shared fixture\n', encoding='utf-8')
        (self.sdk / '__init__.py').write_text('# SDK fixture\n', encoding='utf-8')
        (self.sdk / 'base').mkdir()
        (self.sdk / 'base' / 'exchange.py').write_text('# SDK base fixture\n', encoding='utf-8')
        self.profile = PROFILES['bybit']
        self.value = {
            'schemaVersion': 2, 'kind': 'reviewed_implementation_receipt', 'exchange': 'bybit',
            'ccxtVersion': '4.5.75', 'profileVersion': self.profile.profile_version,
            'profileHash': evidence.expected_profile_hash(self.profile), 'sourceRevision': 'a' * 40,
            'sourceTreeHash': 'b' * 64, 'parityEvidenceHash': 'c' * 64, 'executionReportHash': 'd' * 64,
            'nodeSourcesHash': 'e' * 64, 'testSourcesHash': 'f' * 64, 'fixturesHash': 'a' * 64,
            'executorTreeHash': evidence.python_tree_hash(self.executor),
            'sdkTreeHash': evidence.python_tree_hash(self.sdk, sdk=True),
            'reviewedAt': '2026-01-01T00:00:00Z', 'providerAcceptanceVerified': False,
            'scope': {'product': 'linear_perpetual', 'positionMode': self.profile.position_mode,
                      'marginMode': self.profile.margin_mode, 'settlementAssets': list(self.profile.settlement_preference),
                      'modes': list(self.profile.modes), 'contractSizeRule': 'positive_native_base_multiplier'},
        }

    def save(self, value=None):
        data = json.dumps(self.value if value is None else value).encode()
        path = self.receipts / 'bybit.json'
        path.write_bytes(data)
        return path, hashlib.sha256(data).hexdigest()

    def check(self, value=None):
        return evidence.validate_receipt(self.value if value is None else value, 'bybit', '4.5.75',
                                         self.profile, self.executor, self.sdk)

    def test_complete_bound_fixture_is_valid_but_has_no_approval_by_itself(self):
        self.check()
        path, digest = self.save()
        with self.assertRaisesRegex(evidence.ReceiptError, 'review pin'):
            evidence.read_receipt(path, ())
        self.assertEqual(evidence.read_receipt(path, (digest,)), self.value)
        with patch.object(certification, 'APPROVED_IMPLEMENTATION_RECEIPTS', {}):
            self.assertFalse(certification.certification_result(self.receipts, 'bybit', '4.5.75', self.profile).valid)

    def test_runtime_entrypoint_uses_its_own_paths_and_trusted_pin(self):
        _, digest = self.save()
        with patch.object(certification, 'APPROVED_IMPLEMENTATION_RECEIPTS', {('bybit', 1): (digest,)}), \
             patch.object(certification, '__file__', str(self.executor / 'ccxt_certification.py')), \
             patch.object(certification.ccxt, '__file__', str(self.sdk / '__init__.py')):
            self.assertTrue(certification.certification_result(self.receipts, 'bybit', '4.5.75', self.profile).valid)
            changed = copy.deepcopy(self.value)
            changed['testSourcesHash'] = '1' * 64
            self.save(changed)
            self.assertFalse(certification.certification_result(self.receipts, 'bybit', '4.5.75', self.profile).valid)

    def test_scope_identity_version_and_build_commitments_are_strict(self):
        mutations = [
            ('schemaVersion', True), ('schemaVersion', 1), ('kind', 'certified'), ('exchange', 'hyperliquid'),
            ('ccxtVersion', '4.5.76'), ('profileVersion', True), ('profileVersion', 9),
            ('profileHash', '0' * 64), ('sourceRevision', '../main'), ('nodeSourcesHash', 'bad'),
            ('providerAcceptanceVerified', True), ('reviewedAt', '2999-01-01T00:00:00Z'),
            ('reviewedAt', 'invalid'), ('executorTreeHash', '0' * 64), ('sdkTreeHash', '0' * 64),
        ]
        for key, value in mutations:
            with self.subTest(field=key, value=value):
                changed = copy.deepcopy(self.value)
                changed[key] = value
                with self.assertRaises((evidence.ReceiptError, ValueError)):
                    self.check(changed)
        for key, value in [('modes', ['live']), ('settlementAssets', ['USDT']), ('positionMode', 'hedge'),
                           ('marginMode', 'isolated'), ('product', 'future'), ('contractSizeRule', 'assume_one')]:
            changed = copy.deepcopy(self.value)
            changed['scope'][key] = value
            with self.subTest(scope=key), self.assertRaisesRegex(evidence.ReceiptError, 'scope'):
                self.check(changed)
        for changed in [[], {**self.value, 'extra': True}, {key: value for key, value in self.value.items() if key != 'fixturesHash'}]:
            with self.assertRaises(evidence.ReceiptError):
                self.check(changed)

    def test_source_addition_modification_and_removal_invalidate_the_tree(self):
        file = self.executor / 'adapter.py'
        original = file.read_bytes()
        file.write_bytes(original + b'# changed\n')
        with self.assertRaisesRegex(evidence.ReceiptError, 'source drifted'):
            self.check()
        file.write_bytes(original)
        new = self.executor / 'new_provider.py'
        new.write_text('# new provider\n', encoding='utf-8')
        with self.assertRaisesRegex(evidence.ReceiptError, 'source drifted'):
            self.check()
        new.unlink()
        file.unlink()
        with self.assertRaisesRegex(evidence.ReceiptError, 'source drifted'):
            self.check()

    def test_nested_sdk_change_is_checked_not_only_version(self):
        (self.sdk / 'base' / 'exchange.py').write_text('# drift\n', encoding='utf-8')
        with self.assertRaisesRegex(evidence.ReceiptError, 'SDK source drifted'):
            self.check()

    def test_hardcoded_scope_cannot_certify_a_different_profile_model(self):
        for changes in ({'default_type': 'future'}, {'default_type': 'spot'}, {'default_sub_type': 'inverse'},
                        {'position_mode': 'hedge'}, {'margin_mode': 'isolated'},
                        {'settlement_preference': ('BTC',)}, {'modes': ('paper',)}):
            profile = replace(self.profile, **changes)
            value = copy.deepcopy(self.value)
            value['profileHash'] = evidence.expected_profile_hash(profile)
            value['scope'].update(positionMode=profile.position_mode, marginMode=profile.margin_mode,
                                  settlementAssets=list(profile.settlement_preference), modes=list(profile.modes))
            with self.subTest(changes=changes), self.assertRaises(evidence.ReceiptError):
                evidence.validate_receipt(value, 'bybit', '4.5.75', profile, self.executor, self.sdk)

    def test_only_trusted_approval_file_is_excluded_to_avoid_circular_hash(self):
        authority = self.executor / evidence.AUTHORITY_FILE
        authority.write_text('# trusted pins live separately\n', encoding='utf-8')
        self.check()
        (self.executor / 'ccxt_certification_evidence.py').write_text('# validator\n', encoding='utf-8')
        with self.assertRaisesRegex(evidence.ReceiptError, 'source drifted'):
            self.check()

    def test_legacy_bool_document_cannot_grant_approval_even_if_format_pinned(self):
        value = {'exchange': 'bybit', 'status': 'certified', 'ccxtVersion': '4.5.75', 'profileVersion': 1,
                 'tests': {key: True for key in ('protectedEntry', 'cancel', 'reconciliation', 'stream',
                                                'credentialRotation', 'accountIdentity', 'marketNormalization')}}
        path, digest = self.save(value)
        with self.assertRaisesRegex(evidence.ReceiptError, 'schema'):
            self.check(evidence.read_receipt(path, (digest,)))
        # Negative regression inputs must remain legacy even when real checkout
        # receipts are later independently reviewed and become valid.
        for exchange, profile in PROFILES.items():
            legacy = {**value, 'exchange': exchange, 'profileVersion': profile.profile_version}
            original = json.dumps(legacy).encode('utf-8')
            (self.receipts / f'{exchange}.json').write_bytes(original)
            pins = {(exchange, profile.profile_version): (hashlib.sha256(original).hexdigest(),)}
            with self.subTest(exchange=exchange), patch.object(certification, 'APPROVED_IMPLEMENTATION_RECEIPTS', pins):
                outcome = certification.certification_result(self.receipts, exchange, '4.5.75', profile)
                self.assertFalse(outcome.valid)
                self.assertIn('schema', outcome.reason)

    def test_duplicate_keys_nonfinite_and_oversized_receipts_are_rejected(self):
        for raw in (b'{"a":1,"a":2}', b'{"a":NaN}', b'{"a":Infinity}', b' ' * (64 * 1024 + 1)):
            path = self.receipts / 'bybit.json'
            path.write_bytes(raw)
            with self.assertRaises(evidence.ReceiptError):
                evidence.read_receipt(path, (hashlib.sha256(raw).hexdigest(),))

    def test_malformed_trusted_pin_container_cannot_match_a_substring(self):
        path, digest = self.save()
        for invalid in (digest, 'not-a-pin:' + digest + ':not-a-pin', [digest], (digest, digest),
                        ('A' * 64,), (True,), {'value': digest}, (digest,) * 17):
            with self.subTest(policy=type(invalid).__name__), self.assertRaisesRegex(evidence.ReceiptError, 'pin policy'):
                evidence.read_receipt(path, invalid)

    def test_hardlink_and_file_budget_are_rejected(self):
        path = self.executor / 'adapter.py'
        link = self.executor / 'linked.py'
        os.link(path, link)
        with self.assertRaisesRegex(evidence.ReceiptError, 'ordinary unlinked'):
            evidence.python_tree_hash(self.executor)
        link.unlink()
        with patch.object(evidence, 'MAX_TREE_BYTES', 1), self.assertRaisesRegex(evidence.ReceiptError, 'byte budget'):
            evidence.python_tree_hash(self.executor)
        with self.assertRaisesRegex(evidence.ReceiptError, 'file budget'):
            evidence.file_bytes(path, limit=1)

    def test_invalid_identifiers_and_missing_files_fail_closed_without_raw_details(self):
        result = certification.certification_result(self.receipts, '../bybit', '4.5.75', self.profile)
        self.assertFalse(result.valid)
        self.assertNotIn(str(self.root), result.reason)
        with patch.object(certification, 'APPROVED_IMPLEMENTATION_RECEIPTS', {('bybit', 1): ('a' * 64,)}):
            result = certification.certification_result(self.receipts, 'bybit', '4.5.75', self.profile)
            self.assertFalse(result.valid)
            self.assertNotIn(str(self.root), result.reason)
