export const C_RESET = '\x1b[0m';
export const C_BOLD = '\x1b[1m';
export const C_DIM = '\x1b[2m';
export const C_GREEN = '\x1b[32m';         // Matrix-Grün
export const C_BRIGHT_GREEN = '\x1b[92m';  // Neon-Grün
export const C_DARK_GREEN = '\x1b[2m\x1b[32m'; // Abgedunkeltes Grün für Borders
export const C_WHITE = '\x1b[37m';         // Weiß für Datenwerte/Eingaben
export const C_WHITE_BOLD = '\x1b[1m\x1b[37m';
export const C_RED = '\x1b[31m';           // Warnungen/Fehler
export const C_YELLOW = '\x1b[33m';        // System-Hinweise
export const C_GRAY = '\x1b[90m';          // Inaktives Grau
