"""Build the small read-only catalog projection from the reviewed CCXT matrix.

The projection is display data. It never changes executable exchange profiles.
Run with --check in CI/tests to reject stale generated data.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/testing/ccxt-expansion-matrix.json"
TARGET = ROOT / "src/ccxt_catalog_assessments.ts"
APPROVED_INVENTORY_HASH = "5a76c0381e97811ce155f2eaa523570cabdd0bc0d8e81b72c8950f0d8f0dd69f"
APPROVED_ASSESSMENTS_HASH = "48920351be5a4cae85508e469aab0d9c91b8b805c29d639218fd49014bcc2bff"


def digest(value: object) -> str:
    raw = json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"), allow_nan=False)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def render() -> str:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    inventory = source["inventory"]
    assessments = source["assessments"]
    if (
        source["schemaVersion"] != 1
        or inventory["ccxtVersion"] != "4.5.75"
        or source["inventoryHash"] != APPROVED_INVENTORY_HASH
        or digest(inventory) != APPROVED_INVENTORY_HASH
        or digest(assessments) != APPROVED_ASSESSMENTS_HASH
    ):
        raise ValueError("CCXT matrix differs from the approved pinned review")
    rows = inventory["exchanges"]
    ids = [row["id"] for row in rows]
    if ids != inventory["restIds"] or len(ids) != 103 or [row["id"] for row in assessments] != ids:
        raise ValueError("CCXT matrix is incomplete or its rows are out of order")
    projected = []
    for row, assessment in zip(rows, assessments, strict=True):
        products = sorted({
            f'{scope["product"]}:{scope["settlementType"]}'
            for scope in row["productScopes"]
        })
        projected.append({
            "id": row["id"],
            "products": products,
            "decision": assessment["decision"],
            "reasonCodes": assessment["reasonCodes"],
        })
    payload = {
        "ccxtVersion": inventory["ccxtVersion"],
        "inventoryHash": source["inventoryHash"],
        "assessmentsHash": digest(assessments),
        "entries": projected,
    }
    return (
        "// Generated by scripts/generate_ccxt_catalog_assessments.py; read-only display data.\n"
        "// Do not use this projection to grant trading or account-creation access.\n"
        "export const CCXT_CATALOG_ASSESSMENTS = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + " as const;\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("CCXT catalog assessment projection is stale")
    else:
        TARGET.write_text(expected, encoding="utf-8")
