// Generated by scripts/generate_ccxt_catalog_assessments.py; read-only display data.
// Do not use this projection to grant trading or account-creation access.
export const CCXT_CATALOG_ASSESSMENTS = {
  "ccxtVersion": "4.5.75",
  "inventoryHash": "5a76c0381e97811ce155f2eaa523570cabdd0bc0d8e81b72c8950f0d8f0dd69f",
  "assessmentsHash": "48920351be5a4cae85508e469aab0d9c91b8b805c29d639218fd49014bcc2bff",
  "entries": [
    {
      "id": "alpaca",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "apex",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "external_zklink_signing_sdk_required"
      ]
    },
    {
      "id": "aster",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "accountwide_strategy_parent_scope_unavailable",
        "strategy_history_requires_known_identity"
      ]
    },
    {
      "id": "backpack",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bequant",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bigone",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "binance",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "conditional_orders_removed_from_native_normal_batch"
      ]
    },
    {
      "id": "binancecoinm",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "conditional_orders_removed_from_native_normal_batch"
      ]
    },
    {
      "id": "binanceus",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "binanceusdm",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "conditional_orders_removed_from_native_normal_batch"
      ]
    },
    {
      "id": "bingx",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "stop_market_client_identity_not_provider_proven",
        "batch_failure_collection_not_normalized"
      ]
    },
    {
      "id": "bit2c",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bitbank",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bitbns",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bitfinex",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bitflyer",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bitget",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "preset_stop_ack_has_parent_identity_only",
        "separate_tpsl_requires_shared_child_lifecycle"
      ]
    },
    {
      "id": "bithumb",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bitmex",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "protected_bulk_bespoke_only",
        "new_positions_restricted_during_provider_wind_down"
      ]
    },
    {
      "id": "bitopro",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bitrue",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bitso",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bitstamp",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bitteam",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bittrade",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "bitvavo",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "blockchaincom",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "blofin",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "btcbox",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "btcmarkets",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "btcturk",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "btse",
      "products": [
        "future:linear",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bullish",
      "products": [
        "future:linear",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "bybit",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "accountwide_option_and_preupgrade_history_not_complete",
        "provider_delivery_finality_not_proven",
        "local_profile_remains_quarantined"
      ]
    },
    {
      "id": "bybiteu",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "regional_derivatives_product_not_supported"
      ]
    },
    {
      "id": "bydfi",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "cex",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "coinbase",
      "products": [
        "future:linear",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "coinbaseexchange",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "coinbaseinternational",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "coincheck",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "coinex",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "coinmate",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "coinone",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "coinsph",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "coinspot",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "cryptocom",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "cryptomus",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "deepcoin",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "attached_child_created_after_fill_without_identity",
        "trigger_scope_unpaged_and_pro_event_unhandled"
      ]
    },
    {
      "id": "delta",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "deribit",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "derive",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "digifinex",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "dydx",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "extended",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "attached_child_identity_requires_shared_lifecycle",
        "terminal_zero_fill_retention_not_durable"
      ]
    },
    {
      "id": "fmfwio",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "foxbit",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "gate",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "normal_batch_rejects_stop_leg",
        "native_attached_child_requires_shared_lifecycle"
      ]
    },
    {
      "id": "gateeu",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "regional_derivatives_product_not_supported"
      ]
    },
    {
      "id": "gemini",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "grvt",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "oto_child_activation_requires_full_parent_fill"
      ]
    },
    {
      "id": "hashkey",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "hibachi",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "hitbtc",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "hollaex",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "htx",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "hyperliquid",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "existing",
      "reasonCodes": [
        "master_key_only_scope_locally_reviewed",
        "bound_parity_and_execution_receipt_required"
      ]
    },
    {
      "id": "independentreserve",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "indodax",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "kraken",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "krakenfutures",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "protected_ioc_stop_batch_provider_contract_not_proven",
        "sdk_serialization_is_not_capability_grant",
        "local_profile_remains_quarantined"
      ]
    },
    {
      "id": "kucoin",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "cross_id_identity_not_canonical",
        "parallel_profile_would_split_risk_and_allow_duplicate_execution"
      ]
    },
    {
      "id": "kucoinfutures",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "cross_capacity_requires_new_quote_contract",
        "historical_funding_symbol_universe_not_complete",
        "fill_and_funding_finality_not_proven"
      ]
    },
    {
      "id": "latoken",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "lbank",
      "products": [],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "lighter",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "luno",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "mercado",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "mexc",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "modetrade",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "orderly_bracket_lacks_ioc_semantics",
        "history_and_funding_identity_require_shared_lifecycle"
      ]
    },
    {
      "id": "mudrex",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "myokx",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "attached_ioc_absent_child_requires_shared_lifecycle_contract",
        "regional_xperp_requires_expiry_lifecycle",
        "regional_true_swap_scope_not_proven"
      ]
    },
    {
      "id": "nado",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "ndax",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "okx",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "optional_child_lifecycle_not_representable"
      ]
    },
    {
      "id": "okxus",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "onetrading",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "p2b",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "pacifica",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "paradex",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "paymium",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "phemex",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "poloniex",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "tokocrypto",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "toobit",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "upbit",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "weex",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "attached_stop_has_parent_identity_only",
        "normal_and_algo_domains_require_shared_child_lifecycle"
      ]
    },
    {
      "id": "whitebit",
      "products": [
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    },
    {
      "id": "woo",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "bracket_path_drops_ioc",
        "child_first_ack_and_funding_currency_require_shared_contracts"
      ]
    },
    {
      "id": "woofipro",
      "products": [
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "orderly_bracket_lacks_ioc_semantics",
        "history_and_funding_identity_require_shared_lifecycle"
      ]
    },
    {
      "id": "xt",
      "products": [
        "future:inverse",
        "future:linear",
        "swap:inverse",
        "swap:linear"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "attached_stop_replaces_entry_without_identity",
        "tier_and_mode_admission_require_shared_contracts"
      ]
    },
    {
      "id": "zaif",
      "products": [],
      "decision": "not_derivative",
      "reasonCodes": [
        "pinned_sdk_explicitly_declares_no_derivatives"
      ]
    },
    {
      "id": "zebpay",
      "products": [
        "swap:unknown"
      ],
      "decision": "not_easy",
      "reasonCodes": [
        "pinned_required_native_capability_missing"
      ]
    }
  ]
} as const;
